services:
  postgres:
    image: postgres:15-alpine
    container_name: redact-db
    env_file:
      - .env # ← loads POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB, etc.
    volumes:
      - redact-db-data:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - redact-network

  api:
    build: .
    container_name: node_api
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env # ← now NODE_ENV, PORT, API_KEY, HF_TOKEN, HF_BASE_URL, etc. all come from .env
    volumes:
      - ./src:/app/src
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    networks:
      - redact-network
      - matrix-homeserver

volumes:
  redact-db-data:

networks:
  redact-network:
    driver: bridge

  matrix-homeserver: # 👈 Declare the external network
    external: true
