version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: redact-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - redact-db-data:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - redact-network

  api:
    build: .
    container_name: node_api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - API_KEY=${API_KEY}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - MATRIX_ADMIN_TOKEN=${MATRIX_ADMIN_TOKEN}
      - MATRIX_BASE_URL=${MATRIX_BASE_URL}
      - INSTAGRAM_BOT=${INSTAGRAM_BOT}
      - INSTAGRAM_BOT_TOKEN=${INSTAGRAM_BOT_TOKEN}
    volumes:
      - ./src:/app/src
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    networks:
      - redact-network

volumes:
  redact-db-data:

networks:
  redact-network:
    driver: bridge
