exports.raw = [
  {
    event_id: "$S09FZ2cwcMaqI9BFiKmpYcFUbcHjTHX38vXZu1oqs0A",
    room_id: "!mPqJWpYpRwLazMaeGe:guardii.ai",
    type: "m.room.message",
    sender: "@instagrambot:guardii.ai",
    origin_server_ts: "1752550850068",
    content: {
      body: "⚠️ Your message was not bridged: You're not logged in",
      msgtype: "m.notice",
      "m.mentions": {
        user_ids: ["@prabesh:guardii.ai"],
      },
      "m.relates_to": {
        "m.in_reply_to": {
          event_id: "$rIJ29_0kguGxFo4IMIFcaH80vYO3SE4npLgJF8Cd9Do",
        },
      },
    },
    sender_displayname: "Instagram bridge bot",
  },
  {
    event_id: "$rIJ29_0kguGxFo4IMIFcaH80vYO3SE4npLgJF8Cd9Do",
    room_id: "!mPqJWpYpRwLazMaeGe:guardii.ai",
    type: "m.room.message",
    sender: "@prabesh:guardii.ai",
    origin_server_ts: "1752550849998",
    content: {
      body: "yeah it is",
      msgtype: "m.text",
      "m.mentions": {},
    },
    sender_displayname: "Prabesh",
  },
  {
    event_id: "$95_fKWtZVsasxwl7vPVj-D4cl0refs9XWtTAvwnXY1Q",
    room_id: "!mPqJWpYpRwLazMaeGe:guardii.ai",
    type: "m.room.message",
    sender: "@instagram_17845301208312779:guardii.ai",
    origin_server_ts: "1752492465796",
    content: {
      body: "100 dollor",
      msgtype: "m.text",
      "m.mentions": {},
    },
    sender_displayname: "Whoever Isyou (IG)",
  },
  {
    event_id: "$LmFKefwq8jmXFZf85iAsh1OfmQ54IFlSgJcG2fxU-hI",
    room_id: "!mPqJWpYpRwLazMaeGe:guardii.ai",
    type: "m.room.message",
    sender: "@prabesh:guardii.ai",
    origin_server_ts: "1752492453385",
    content: {
      body: "how much for 10gm?",
      msgtype: "m.text",
      "m.mentions": {},
    },
    sender_displayname: "Prabesh",
  },
  {
    event_id: "$qp4i25KhNkmj2wbgRTHehqgGlp3feSzhvqDPgloNIk4",
    room_id: "!mPqJWpYpRwLazMaeGe:guardii.ai",
    type: "m.room.message",
    sender: "@prabesh:guardii.ai",
    origin_server_ts: "1752492445714",
    content: {
      body: "what about canabis ?",
      msgtype: "m.text",
      "m.mentions": {},
    },
    sender_displayname: "Prabesh",
  },
  {
    event_id: "$aemBhkqV3kJvtEKpAMlrD6RxHOHfXeUhoL70OFtXg7Q",
    room_id: "!mPqJWpYpRwLazMaeGe:guardii.ai",
    type: "m.room.message",
    sender: "@instagram_17845301208312779:guardii.ai",
    origin_server_ts: "1752492424379",
    content: {
      body: "how much do you need?",
      msgtype: "m.text",
      "m.mentions": {},
    },
    sender_displayname: "Whoever Isyou (IG)",
  },
  {
    event_id: "$H8xXps4VRD0o8iec_ZDn6-whIGcXJBZBUNUN6lZ6gsY",
    room_id: "!mPqJWpYpRwLazMaeGe:guardii.ai",
    type: "m.room.message",
    sender: "@instagram_17845301208312779:guardii.ai",
    origin_server_ts: "1752492418345",
    content: {
      body: "LSD would cost you around  10K?",
      msgtype: "m.text",
      "m.mentions": {},
    },
    sender_displayname: "Whoever Isyou (IG)",
  },
  {
    event_id: "$GK0bnWt7vHpiAmmrlrDUG0ln5OSaihOZ-h2KInYAyXY",
    room_id: "!mPqJWpYpRwLazMaeGe:guardii.ai",
    type: "m.room.message",
    sender: "@prabesh:guardii.ai",
    origin_server_ts: "1752492381362",
    content: {
      body: "how much ?",
      msgtype: "m.text",
      "m.mentions": {},
    },
    sender_displayname: "Prabesh",
  },
  {
    event_id: "$sbQ6kFfBNvo_v6yi2mDPhX55VWmyTvaI2MaA50BT1iM",
    room_id: "!mPqJWpYpRwLazMaeGe:guardii.ai",
    type: "m.room.message",
    sender: "@prabesh:guardii.ai",
    origin_server_ts: "1752492376493",
    content: {
      body: "LSD would be fine",
      msgtype: "m.text",
      "m.mentions": {},
    },
    sender_displayname: "Prabesh",
  },
  {
    event_id: "$9_OI7vTqUq9GR92anF0Siykg8wK7S7u8BtirZkmkuAU",
    room_id: "!mPqJWpYpRwLazMaeGe:guardii.ai",
    type: "m.room.message",
    sender: "@instagram_17845301208312779:guardii.ai",
    origin_server_ts: "1752492348124",
    content: {
      body: "LSD? Xan ?",
      msgtype: "m.text",
      "m.mentions": {},
    },
    sender_displayname: "Whoever Isyou (IG)",
  },
  {
    event_id: "$HKNNMdXhbf3KQfTSVxqcKnddAprdhDtwhgqs7xFK45Y",
    room_id: "!mPqJWpYpRwLazMaeGe:guardii.ai",
    type: "m.room.message",
    sender: "@instagram_17845301208312779:guardii.ai",
    origin_server_ts: "1752490122834",
    content: {
      body: "which do you need ?",
      msgtype: "m.text",
      "m.mentions": {},
    },
    sender_displayname: "Whoever Isyou (IG)",
  },
  {
    event_id: "$HIYYdWtKVRVAsU7DXcHPGq0jlvESddnWi7wYIEJBeHQ",
    room_id: "!mPqJWpYpRwLazMaeGe:guardii.ai",
    type: "m.room.message",
    sender: "@instagram_17845301208312779:guardii.ai",
    origin_server_ts: "1752490119016",
    content: {
      body: "yeah I have some",
      msgtype: "m.text",
      "m.mentions": {},
    },
    sender_displayname: "Whoever Isyou (IG)",
  },
  {
    event_id: "$2Sm3QNHfBvDJieXRs0V41-9qfnvdBscT-GCgVSTvPeU",
    room_id: "!mPqJWpYpRwLazMaeGe:guardii.ai",
    type: "m.room.message",
    sender: "@prabesh:guardii.ai",
    origin_server_ts: "1752490096538",
    content: {
      body: "do you have some drugs?",
      msgtype: "m.text",
      "m.mentions": {},
      "fi.mau.double_puppet_ts": 1752490096538,
      "fi.mau.double_puppet_source": "mautrix-meta",
    },
    sender_displayname: "Prabesh",
  },
  {
    event_id: "$GK8l5KUmhO_agmF1KhokJk48w40ojJFqiJTI8lBvB58",
    room_id: "!mPqJWpYpRwLazMaeGe:guardii.ai",
    type: "m.room.message",
    sender: "@instagram_17845301208312779:guardii.ai",
    origin_server_ts: "1752490015643",
    content: {
      body: "the the",
      msgtype: "m.text",
      "m.mentions": {},
    },
    sender_displayname: "Whoever Isyou (IG)",
  },
  {
    event_id: "$VzlhKxEbT90nBCbVAI8eh71l-azmgKb-hfy75gL0O_s",
    room_id: "!mPqJWpYpRwLazMaeGe:guardii.ai",
    type: "m.room.message",
    sender: "@instagram_17845301208312779:guardii.ai",
    origin_server_ts: "1752490012321",
    content: {
      body: "doing nothing",
      msgtype: "m.text",
      "m.mentions": {},
    },
    sender_displayname: "Whoever Isyou (IG)",
  },
  {
    event_id: "$DfbLe2zM9O5_4_GG7l4X0ehKPwJhl2xBpe7HM6oKaXk",
    room_id: "!mPqJWpYpRwLazMaeGe:guardii.ai",
    type: "m.room.message",
    sender: "@instagram_17845301208312779:guardii.ai",
    origin_server_ts: "1752490008979",
    content: {
      body: "Im also all good",
      msgtype: "m.text",
      "m.mentions": {},
    },
    sender_displayname: "Whoever Isyou (IG)",
  },
  {
    event_id: "$1-tkt4Om1Z1333kKcYkJb2GXIXY3tWHRrYQD4K3aIgQ",
    room_id: "!mPqJWpYpRwLazMaeGe:guardii.ai",
    type: "m.room.message",
    sender: "@prabesh:guardii.ai",
    origin_server_ts: "1752489958537",
    content: {
      body: "what about you?",
      msgtype: "m.text",
      "m.mentions": {},
      "fi.mau.double_puppet_ts": 1752489958537,
      "fi.mau.double_puppet_source": "mautrix-meta",
    },
    sender_displayname: "Prabesh",
  },
  {
    event_id: "$vOcxu-tJyCDeJr7RVK4SbhkzScoHj-JrwSVYH7uYoxc",
    room_id: "!mPqJWpYpRwLazMaeGe:guardii.ai",
    type: "m.room.message",
    sender: "@prabesh:guardii.ai",
    origin_server_ts: "1752489953087",
    content: {
      body: "all good",
      msgtype: "m.text",
      "m.mentions": {},
      "fi.mau.double_puppet_ts": 1752489953087,
      "fi.mau.double_puppet_source": "mautrix-meta",
    },
    sender_displayname: "Prabesh",
  },
  {
    event_id: "$WLIcL4yR_cY3VZ-32dIjP-5uwbZd6Aqie7BtYRAkads",
    room_id: "!mPqJWpYpRwLazMaeGe:guardii.ai",
    type: "m.room.message",
    sender: "@prabesh:guardii.ai",
    origin_server_ts: "1752489951780",
    content: {
      body: "im fine",
      msgtype: "m.text",
      "m.mentions": {},
      "fi.mau.double_puppet_ts": 1752489951780,
      "fi.mau.double_puppet_source": "mautrix-meta",
    },
    sender_displayname: "Prabesh",
  },
  {
    event_id: "$8jujcmbl6iHtfU15ERdSwGYT465gjllwtUC3NR-lDjg",
    room_id: "!mPqJWpYpRwLazMaeGe:guardii.ai",
    type: "m.room.message",
    sender: "@instagram_17845301208312779:guardii.ai",
    origin_server_ts: "1752489857528",
    content: {
      body: "How the work going on?",
      msgtype: "m.text",
      "m.mentions": {},
    },
    sender_displayname: "Whoever Isyou (IG)",
  },
];
